[package]
name = "rxy_web_dom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rxy_core = { workspace = true, default-features = false, features = ["web_dom", "common_renderer", "attr_index_u16"] }
hashbrown = "0.14"
#count-macro.workspace = true
#paste.workspace = true
#
#async-channel.workspace = true
#smallvec.workspace = true
#futures-lite.workspace = true
#
#oneshot.workspace = true

#xy_reactive = { workspace = true, optional = true, features = ["web"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures.workspace = true
slotmap.workspace = true
web-sys.workspace = true
paste.workspace = true